### ISSUE TITLE
how do you use the 14 channels images to the CNN?

### ISSUE THREAD

**Issue by wenjuntan** [PRBonn/bonnet#16]
Hello，I have read your paper, in your paper, the 14 channels image are used, but, what should I do to achieve it？

**Comment by tano297** [comment]
The implementation of the extra representations is in the codebase, but in order to make the framework more general, I had to strip it out of the multi-dimensional support. I was working on a way to put in the possibility in a nice way again, but I haven't had time. It should not be hard to add again, so if you want to create a pull request with an initial estimate, do so, and we can figure it out together.

**Comment by louisflorentin** [comment]
Hi, thanks for your GREAT framework, it is really useful for me. I am trying to implement the 14 channels and I would like to know what parameters you chose in the model (14 channels) you present in your article. Could you please share your cfg files (net.yaml, train.yaml) ? I attached my cfg files, which don't lead to an efficient model. Thank you very much.

![net yaml](https://user-images.githubusercontent.com/64954736/96013629-c5dc1800-0e45-11eb-9b95-d753f4010656.png)
![train yaml](https://user-images.githubusercontent.com/64954736/96013633-c674ae80-0e45-11eb-8d8f-f4762d82763c.png)
