### ISSUE TITLE
Question about Input Image Size and PSPNet Support

### ISSUE THREAD

**Issue by haopo2005** [PRBonn/bonnet#26]
Hi,
I find you have implemented erfnet for training. I'd like to know whether I can use custom size of input image to training? Do I need to modify something?
And does bonnet support pspnet now?

**Comment by tano297** [comment]
Hi there,

As for the input size, you can use anyone you desire, as long as it is divisible by the output stride of the encoder. In the case of erfnet it is 8. 

The reason why I didn't specifically call the architecture erfnet is because even though I used the residuals non-bottlenecks from them, I could not implement the dilated convolutions (tensortt doesn't support them) and therefore there is a slight accuracy loss in the bigger object classes. 

I currently have no plans to implement pspnet because with the resnet backend you can't do realtime, even in a 1080ti. However, you can implement the pyramid pooling module into one of the efficient architectures we have now by using the layer described in the arch directory.
